//# sourceMappingURL=_.js.map
(function(d){d._lastObj=null;d._modLoaded=[];d._eventStore=[];d._watchStore={};d._temporary=null;var f=function(a){return new m(a)},m=function(a){var c="undefined"!==typeof exports||"undefined"===typeof a?[]:-1===a.indexOf(">")?document.querySelectorAll(a):[];this.selector=1===c.length?c[0]:c;this.length=c.length;this.param=a;this._watchStore={};this.version="1.0.0";this.revision="r180828";this.fullversion=this.version+this.revision;this.isBeta=this.version.match(/b/g);this.isCompiled=!1;this.isStable=
!this.isBeta;this.ScriptRX="<script[^>]*>([\\S\\s]*?)\x3c/script\\s*>";this.JSONRX="/^/*-secure-([sS]*)*/s*$/";this.nodeJS="undefined"!==typeof exports;this.emoij={nerd:"\ud83e\udd13",smilie:"\ud83d\ude03",dsmilie:"\ud83d\ude00",heart:"\u2764\ufe0f",brokenheart:"\ud83d\udc94"};this.objectclass={"[object Boolean]":"boolean","[object Number":"number","[object String":"string","[object Function]":"function","[object Array]":"array","[object Date]":"date","[object RegExp]":"regexp","[object Object]":"object",
"[object Error]":"error"};this.cconsole={reset:{start:"\u001b[0m",stop:"\u001b[0m"},bold:{start:"\u001b[1m",stop:"\u001b[22m"},dim:{start:"\u001b[2m",stop:"\u001b[22m"},italic:{start:"\u001b[3m",stop:"\u001b[23m"},underline:{start:"\u001b[4m",stop:"\u001b[24m"},inverse:{start:"\u001b[7m",stop:"\u001b[27m"},hidden:{start:"\u001b[8m",stop:"\u001b[28m"},strikethrough:{start:"\u001b[9m",stop:"\u001b[29m"},color:{standard:"\u001b[39m",black:"\u001b[30m",red:"\u001b[31m",green:"\u001b[32m",yellow:"\u001b[33m",
blue:"\u001b[34m",magenta:"\u001b[35m",cyan:"\u001b[36m",white:"\u001b[37m",gray:"\u001b[90m"},background:{standard:"\u001b[49m",black:"\u001b[40m",red:"\u001b[41m",green:"\u001b[42m",yellow:"\u001b[43m",blue:"\u001b[44m",magenta:"\u001b[45m",cyan:"\u001b[46m",white:"\u001b[47m"}};a=this.nodeJS?{userAgent:"Node.js Node.js Node.js",maxTouchPoints:0,msMaxTouchPoints:0}:window.navigator;var b="Chrome"===a.userAgent.split(" ")[a.userAgent.split(" ").length-2].split("/")[0]?a.userAgent.split(" ")[a.userAgent.split(" ").length-
2].split("/")[0]:a.userAgent.split(" ")[a.userAgent.split(" ").length-1].split("/")[0];this.browser={ie:-1!==a.userAgent.indexOf("Trident"),firefox:"Firefox"===b,safari:"Safari"===b,opera:"OPR"===b,edge:"Edge"===b,chrome:"Chrome"===b,userAgent:a.userAgent,supportTouch:"ontouchstart"in d||0<a.maxTouchPoints||0<a.msMaxTouchPoints};this.getBrowser=b;this.title=this.tagName=this.tabIndex=this.style=this.scrollWidth=this.scrollHeight=this.scrollTop=this.scrollLeft=this.prototype=this.previousSibling=this.prefix=
this.parentNode=this.ownerDocument=this.offsetHeight=this.offsetWidth=this.offsetParent=this.offsetTop=this.offsetLeft=this.nodeValue=this.nodeType=this.nodeName=this.nextSibling=this.namespaceURI=this.localName=this.lastChild=this.lang=this.innerHTML=this.id=this.firstChild=this.dir=this.clientWidth=this.clientHeight=this.className=this.childNodes=this.attributes=void 0;this.copyItems="attributes childNodes className clientHeight clientWidth dir firstChild id innerHTML lang lastChild localName namespaceURI nextSibling nodeName nodeType nodeValue offsetLeft offsetTop offsetParent offsetWidth offsetHeight ownerDocument parentNode prefix previousSibling prototype scrollLeft scrollTop scrollHeight scrollWidth style tabIndex tagName title".split(" ");
for(a=0;a<this.copyItems.length;a++)"undefined"!==typeof c[0]&&"undefined"!==typeof c[0][this.copyItems[a]]&&(this[this.copyItems[a]]=c[0][this.copyItems[a]]);for(a=0;a<this.length;a++)this[a]=c[a],d._lastObj=c[a];return this};f.fn=m.prototype={_:function(a){return this[a]},emulatejQuery:function(){d.$=d._;d._$=d._;d.jQuery=d._;return d._jQuery=d._},$:function(a){f.nodeJS?"TEST"!==a&&console.log("Thanks for using '_.js'!\n"+decodeURIComponent("%F0%9F%92%99")):(d.alert("Hi"),d.confirm("Did you know that i'm not jQuery?")?
d.alert("Why did you even try this?"):d.alert("Nope, i'm not jQuery"),d.alert("Thanks for using '_.js'!\n"+decodeURIComponent("%F0%9F%92%99")))},extend:function(){var a,c,b,e,d,f=arguments[0]||{},h=1,l=arguments.length,n=!1;"boolean"===typeof f&&(n=f,f=arguments[h]||{},h++);"object"===typeof f||this.isFunction(f)||(f={});h===l&&(f=this,h--);for(;h<l;h++)if(null!=(d=arguments[h]))for(e in d)a=f[e],b=d[e],f!==b&&(n&&b&&(this.isPlainObject(b)||(c=this.isArray(b)))?(c?(c=!1,a=a&&this.isArray(a)?a:[]):
a=a&&this.isPlainObject(a)?a:{},f[e]=this.extend(n,a,b)):void 0!==b&&(f[e]=b));return f},isArray:function(a){return(f.nodeJS?!1:a.isArray)||"array"===this.type(a)},getCookie:function(a){if(f.nodeJS)return!1;var c=document.cookie.indexOf(a+"="),b=c+a.length+1;if(!c&&a!==document.cookie.substring(0,a.length)||-1===c)return null;a=document.cookie.indexOf(";",b);-1===a&&(a=document.cookie.length);return unescape(document.cookie.substring(b,a))},setCookie:function(a,c,b,e,g,k){if(f.nodeJS)return!1;if(!g){var h=
d.location.hostname,h=g.split(".");g=".";for(var l=1;l<h.lenth;l++)g+=h[l]}h=new Date;h.setTime(h.getTime());"string"!==typeof b&&(b=1);"string"!==typeof e&&(e="/");"boolean"!==typeof k&&(k=!1);b&&(b*=864E5);h=new Date(h.getTime()+b);document.cookie=a+"="+escape(c)+(b?";expires="+h.toGMTString():"")+(e?";path="+e:"")+(g?";domain="+g:"")+(k?";secure":"");return null},deleteCookie:function(a,c,b){if(f.nodeJS)return!1;if(this.getCookie(a)){if(!b){c=d.location.hostname;c=b.split(".");b=".";for(var e=
1;e<c.lenth;e++)b+=c[e]}document.cookie=a+"=;expires=Thu, 01-Jan-1970 00:00:01 GMT";return!0}return!1},toggle:function(){if(f.nodeJS)return!1;for(var a=this.length;a--;)this[a].style.display="none"!==this[a].style.display?"none":"";return null},on:function(a,c){if(f.nodeJS)return!1;var b=this.length;if("function"===typeof c)for(;b--;){if("change"===a||"AJAX"===a){f._watchStore[this.param]=[this[b].innerHTML,c];return}this[b].addEventListener(a,c);d._eventStore.push([d._eventStore.length+1,this[b],
a,c])}else for(;b--;){var e=[],g;for(g in d._eventStore)g=d._eventStore[g],this[b]===g[1]&&a===g[2]?g[1].removeEventListener(g[2],g[3]):e.push(g);d._eventStore=e}return null},watchEvents:function(){this.nodeJS?console.warn("_.watchEvents() is only for WEB"):Object.keys(f._watchStore).forEach(function(a){f(a).html()!==f._watchStore[a][0]&&(f._watchStore[a][1](),delete f._watchStore[a])})},noop:function(){},supportTouch:function(){return this.nodeJS?!1:"ontouchstart"in window||0<navigator.maxTouchPoints||
0<navigator.msMaxTouchPoints},appendTo:function(a){if(f.nodeJS)return!1;"body"===a?document.body.innerHTML+=this.param:"head"===a?document.head.innerHTML+=this.param:"."===a.substr(0,1)||"#"===a.substr(0,1)?f(a).html(this.param,!0):this._error("appendTo");return null},_error:function(a,c){"#IGNORE#ME"!==a&&("undefined"===typeof c?console.error("_.js Error: Invalid usage of function"):console.error("_.js Error: "+c),this.startsWith(a,"#")?console.error("Please see: https://github.com/wdg/_.js/wiki/module_"+
a.substr(1)):this.isBeta?console.error("Please see: https://github.com/wdg/_.js/wiki/flbeta_function_"+a):console.error("Please see: https://github.com/wdg/_.js/wiki/function_"+a));return null},deprecated:function(a,c,b,e){console.warn(this.format("\u26a0\ufe0f  function '%s' is deprecated since v%s %s\n               this function will be removed in v%s %s\n%s",a,c,"(https://github.com/wdg/_.js/wiki/changed_in_"+c.replace(/(\.|b|a)/g,"")+")",b,"(https://github.com/wdg/_.js/wiki/changed_in_"+b.replace(/(\.|b|a)/g,
"")+")","undefined"===typeof e?"\n There's no alternative for "+a:"\nAlternative: _."+e+"(...) See https://github.com/wdg/_.js/wiki/"+(this.isBeta?"flbeta_":"")+"function_"+e+" for more information"));return null},error:function(a){if(f.nodeJS)console.error(a);else throw Error(a);},isFunction:function(a){return"function"===this.type(a)},type:function(a){return null==a?a+"":"object"===typeof a||"function"===typeof a?this.objectclass[Object.prototype.toString.call(a)]||"object":typeof a},escapeForRegex:function(a){return a.replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,
"\\$1").replace(/\x08/g,"\\x08")},isPlainObject:function(a){var c,b={}.hasOwnProperty;if(!a||"object"!==this.type(a)||a.nodeType)return!1;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(e){return!1}if({}.ownLast)for(c in a)return b.call(a,c);for(c in a);return void 0===c||b.call(a,c)},evaluate:function(a){if(f.nodeJS)return require("vm").runInThisContext(a);var c=document.createElement("script");c.appendChild(document.createTextNode(a));
document.body.appendChild(c);return!0},require:function(a,c,b){if("object"===typeof a)for(b=a.length-1;0<=b;b--)if(-1===d._modLoaded.indexOf(a[b]))if(d._modLoaded.push(a[b]),a[b].match(/\.js/g)||(a[b]+=".js"),this.startsWith(a[b],"_")&&!this.isLocal()&&(a[b]="https://raw.githubusercontent.com/wdg/_.js/master/latest/modules/"+a[b].toLowerCase()),f.nodeJS){if(this._NodeAjaxHelper(a[b],this.evaluate),b===a.length-1)return f._copy_js(),c()}else{var e=document.createElement("script");e.type="text/javascript";
e.src=a[b];1===b&&(e.onreadystatechange="",e.onload=setTimeout(function(a){f._copy_js();a()},10,c));document.head.appendChild(e)}else f._copy_js(),c();else if("string"===typeof a)if(-1===d._modLoaded.indexOf(a)){d._modLoaded.push(a);a.match(/\.js/g)||(a+=".js");this.startsWith(a,"_")&&!this.isLocal()&&(a="https://raw.githubusercontent.com/wdg/_.js/master/latest/modules/"+a.toLowerCase());if(f.nodeJS)return this._NodeAjaxHelper(a,this.evaluate);b=document.createElement("script");b.type="text/javascript";
b.src=a;b.onreadystatechange="";b.onload=setTimeout(function(a){f._copy_js();a()},10,c);document.head.appendChild(b)}else f._copy_js(),c();else console.error("Please use only a array, or a string.");return null},hide:function(){if(f.nodeJS)return!1;for(var a=this.length;a--;)d._lastObj=this[a],this[a].style.display="none";return this},show:function(){if(f.nodeJS)return!1;for(var a=this.length;a--;)d._lastObj=this[a],this[a].style.display="block";return this},format:function(){var a=arguments,c=1;
return a[0].replace(/%((%)|s|d)/g,function(b){var e=null;if(b[2])e=b[2];else{e=a[c];switch(b){case "%d":e=parseFloat(e),isNaN(e)&&(e=0)}c++}return e})},html:function(a,c){if(f.nodeJS)return!1;for(var b=this.length;b--;){d._lastObj=this[b];if("undefined"===typeof a)return this[b].innerHTML;this[b].innerHTML="undefined"===typeof c?a:this[b].innerHTML+a}return this},framebreak:function(){f.nodeJS||d.top.location===d.location||(d.top.location.href=document.location.href);return!1},ajaxPOST:function(a,
c){if(!f.nodeJS)for(var b=this.length;b--;){d._lastObj=this[b];var e,g=this[b];window._tParam=this.param;e=d.XMLHttpRequest?new d.XMLHttpRequest:new d.ActiveXObject("Microsoft.XMLHTTP");var k=new FormData(a);e.open("POST",a.action,!0);e.upload.onprogress=function(a){a.lengthComputable&&console.log("Progress = "+a.loaded/a.total*100+"%")};e.onreadystatechange=function(){if(4===e.readyState&&200===e.status){g.innerHTML=e.responseText;for(var a=g.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)f.evaluate(a[b].innerHTML);
a=g.getElementsByTagName("form");b=0;for(c=a.length;b<c;b++)"post"===a[b].method.toLowerCase()&&a[b].setAttribute("onsubmit","event.preventDefault();_('"+window._tParam+"').ajaxPOST(this);")}};e.send(k)}return!1},ajax:function(a,c){if(f.nodeJS)return f._NodeAjaxHelper(a,function(a){return a});for(var b=this.length;b--;){d._lastObj=this[b];var e,g=this[b];window._tParam=this.param;e=d.XMLHttpRequest?new d.XMLHttpRequest:new d.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){if(4===
e.readyState&&200===e.status){var a="";g.innerHTML=e.responseText;for(var b=g.getElementsByTagName("form"),c=0,d=b.length;c<d;c++)"post"===b[c].method.toLowerCase()&&b[c].setAttribute("onsubmit","event.preventDefault();_('"+window._tParam+"').ajaxPOST(this);");b=g.getElementsByTagName("script");c=0;for(d=b.length;c<d;c++)a+=f.evaluate(b[c].innerHTML);return a}};e.open("GET",a,!0);e.send()}return!1},_NodeAjaxHelper:function(a,c){if(-1<a.toLowerCase().indexOf("https://"))require("https").get(a,function(a){a.setEncoding("utf8");
var e="";if(-1<[301,302].indexOf(a.statusCode))return"function"===typeof c?f.ajax(a.headers.location,c):f._NodeAjaxHelper(a.headers.location);if(-1<[404,403].indexOf(a.statusCode))return"function"===typeof c?c(!1):!1;a.on("data",function(a){e+=a});a.on("end",function(){return"function"===typeof c?c(e):e})}).on("error",function(a){console.error("Error: "+a);return"function"===typeof c?c(!1):!1});else require("http").get(a,function(a){a.setEncoding("utf8");var e="";if(200!==a.statusCode)return console.error("Request Failed.\nStatus Code: "+
a.statusCode),"function"===typeof c?c(!1):!1;a.on("data",function(a){e+=a});a.on("end",function(){return"function"===typeof c?c(e):e})}).on("error",function(a){console.error("Got error: "+a.message);return"function"===typeof c?c(!1):!1});return!1},noConflict:function(){"object"===typeof q&&(d._=q);return f},requireSSL:function(){f.nodeJS||"https:"===d.location.protocol||"file:"===d.location.protocol||d.location.href.match(/(localhost|127\.0\.0\.1|::1)/g)||(d.location.href="https:"+d.location.href.substring(d.location.protocol.length))},
isUndefined:function(a){return"undefined"===typeof a},isEmpty:function(a){return""===a},isBlank:function(a){return/^\s*$/.test(a)},getFileSize:function(a,c){if(!f.nodeJS)for(var b=this.length;b--;){var e;e=d.XMLHttpRequest?new d.XMLHttpRequest:new d.ActiveXObject("Microsoft.XMLHTTP");e.open("HEAD",a,!0);e.onreadystatechange=function(){4===e.readyState&&(200===e.status?"function"===typeof c?c(e.getResponseHeader("Content-Length")/1024):f(c).html(e.getResponseHeader("Content-Length")/1024):"function"===
typeof c?c("Error while getting filesize"):f(c).html("Error while getting filesize"))};e.send(null)}return null},stripTags:function(){if(!f.nodeJS)for(var a=this.length;a--;)d._lastObj=this[a],this[a].innerHTML=this[a].innerHTML.replace(/<\w+(\s+("[^"]*"|'[^']*'|[^>])+)?>|<\/\w+>/gi,"");return this.nodeJS?!1:null},stripScripts:function(){if(!f.nodeJS)for(var a=this.length;a--;)d._lastObj=this[a],this[a].innerHTML=this[a].innerHTML.replace(new RegExp(this.ScriptRX,"img"),"");return this.nodeJS?!1:
null},css:function(a,c){if(f.nodeJS)return!1;for(var b=this.length;b--;){d._lastObj=this[b];if(this.isUndefined(c))return this[b].style.cssText;for(var e=this[b].style.cssText.split(";"),g="",k=!1,h=0,l="";h<e.length;)this.startsWith(a,e[h])?(l=e[h].split(":"),g=g+l[0]+": "+c+"; ",k=!0):g=g+e[h]+"; ",h++;this[b].style.cssText=k?this[b].style.cssText+a+":"+c+";":g;return this}},escapeHTML:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},unescapeHTML:function(a){return a.replace(/&lt;/g,
"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")},toArray:function(a){if("string"===typeof a)return a.split("");var c=[],b;for(b in a)a.hasOwnProperty(b)&&c.push(a[b]);return c},runTest:function(a,c){return"function"!==typeof a?String(a)===String(c):String(a())===String(c)},includes:function(a,c){return-1<String(a).indexOf(c)},startsWith:function(a,c){return 0===a.lastIndexOf(c,0)},isLocal:function(){return f.nodeJS?!0:"file:"!==d.location.protocol?d.location.href.match(/(file:\/\/|localhost|127\.0\.0\.1|::1)/g)?
!0:!1:!0},endsWith:function(a,c){var b=a.length-c.length;return 0<=b&&a.indexOf(c,b)===b},capitalize:function(a){return a.charAt(0).toUpperCase()+a.substring(1).toLowerCase()},camelize:function(a){return a.replace(/-+(.)?/g,function(a,b){return b?b.toUpperCase():""})},scrollToBottom:function(){if(f.nodeJS)return!1;for(var a=this.length;a--;)d._lastObj=this[a],this[a].scrollTop=this[a].scrollHeight;return!0},scrollToTop:function(){if(f.nodeJS)return!1;for(var a=this.length;a--;)d._lastObj=this[a],
this[a].scrollTop=0;return!0},map:function(a,c){for(var b=[],e=0;e<a.length;e++){var d=c(e,a[e]);if("undefined"===typeof d)f.error("ERROR WHILE MAPPING");else if("string"===typeof d[0])for(var k=0;k<d.length;k++)b.push(d[k]);else b.push(c(e,a[e]))}return b},each:function(a,c){var b=[],e=0,d;for(d in a)a.hasOwnProperty(d)&&(isNaN(d)?b.push(c(d,a[d])):(b.push(c(e,a[d])),e++));return b},merge:function(){for(var a={},c,b=0;b<arguments.length;b++)for(c in arguments[b])arguments[b].hasOwnProperty(c)&&(a[c]=
arguments[b][c]);return a},clearScreen:function(){this.nodeJS?process.stdout.write("\u001bc"):console.warn("_.clearScreen() is only for CLI")},oneLineUp:function(){this.nodeJS?process.stdout.write("\r\u001b[K"):console.warn("_.clearScreen() is only for CLI")},truncate:function(a,c){if(f.nodeJS)return!1;for(var b=this.length;b--;)d._lastObj=this[b],a=a||30,c=this.isUndefined(c)?"...":c,this[b].innerHTML=this[b].innerHTML.length>a?this[b].innerHTML.substring(0,a)+c:String(this[b].innerHTML);return!0},
infinitescroll:function(a){for(var c=this.length;c--;)this[c].addEventListener("scroll",function(b){console.log(this.scrollHeight);this.scrollTop+this.clientHeight+250>=this.scrollHeight&&("function"===typeof a?a():f._error("infinitescroll"))})},_copy_js:function(){var a=new m,c;for(c in a)f[c]=a[c];return null}};var r=new m,p;for(p in r)f[p]=r[p];if(void 0!==d._){console.log("[_.JS Warning] We have overwritten self._!");var q=d._}d._=f;d._s=f;"undefined"!==typeof exports&&(module.exports=f,global._=
f);return f})("undefined"===typeof exports?window:module.exports);if("undefined"===typeof exports&&"undefined"!==typeof document.createEvent){var _JSLoaded=document.createEvent("CustomEvent");_JSLoaded.initEvent("_.jsLoaded",!0,!0,{});window.dispatchEvent(_JSLoaded);window.setInterval("_.watchEvents()",1E3)};
