//# sourceMappingURL=node.js.map
var _=require("./_.js"),delay=10,fillScreen=function(d){for(var b=process.stdout.columns,e=d.length,a="",c=1;c<b-e;c++)a+=" ";process.stdout.write(d+a)};console.log("Terminal size: "+process.stdout.columns+"x"+process.stdout.rows);var _testCounter=1,_timeoutCounter=1,_testPassed=0,_testFailed=0;
function __RunTest(d,b,e){setTimeout(function(a,c,d){if("TOTAL"===a&&"TOTAL"===c)fillScreen("\rAll tests finished"),0<_testFailed?(console.log("\n"+_.cconsole.color.green+_testPassed+" tests Passed (? %)"+_.cconsole.color.standard),console.log("\n"+_.cconsole.color.red+_testFailed+" tests Failed (? %)"+_.cconsole.color.standard)):console.log("\n"+_.cconsole.color.green+_testPassed+" (ALL) tests Passed (100 %)"+_.cconsole.color.standard);else{var b=String(eval(a)).replace(/(\r\n|\n\r|\r|\n)/g,"");
"undefined"!==typeof d||_.runTest(b,String(c).replace(/(\r\n|\n\r|\r|\n)/g,""))?(0===_testFailed&&(process.stdout.write("\u001bc"),console.log(_.cconsole.color.standard+"**"),console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"                         _"),console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"                        (_)"),console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"                         _    _____"),console.log(_.cconsole.color.standard+
"**"+_.cconsole.color.cyan+"                        | |  / ____|"),console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"                        | |  | (___"),console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"                    _   | |  \\___  \\"),console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"     ______    _   | |__| |  ____) |"),console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"    |______|  (_)   \\____/  |______/"),_.version.match(/b/)?
console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"                         v"+_.version.split("b")[0]+" Beta"):console.log(_.cconsole.color.standard+"**"+_.cconsole.color.cyan+"                      v"+_.version+" Release"),console.log(_.cconsole.color.standard+"**              JS Standard Code Style"),console.log(_.cconsole.color.standard+"**"),console.log(_.cconsole.color.standard+"**    This is the Node.js init file."),console.log(_.cconsole.color.standard+"**    To use "+_.cconsole.color.cyan+
"_.js"+_.cconsole.color.standard+" in your project use:"),console.log(_.cconsole.color.standard+"**       "+_.cconsole.color.magenta+"var _ = require('./_.js')"+_.cconsole.color.standard),console.log(_.cconsole.color.standard+"**"),console.log(_.cconsole.color.standard+"**"),console.log(""),console.log("")),process.stdout.write("Expecting: "+_.cconsole.color.green+String(c).replace(/(\r\n|\n\r|\r|\n)/g,"")+_.cconsole.color.standard+"; Got: "+_.cconsole.color.green+b+_.cconsole.color.standard+"\r"),
10>_testCounter?_testCounter="00"+_testCounter:100>_testCounter?_testCounter="0"+_testCounter:_.noop(),fillScreen("\r"+_.cconsole.color.green+"Test (#"+_testCounter+") "+a+" passed"+_.cconsole.color.standard),_testCounter++,_testPassed++):(10>_testCounter?_testCounter="0"+_testCounter:100>_testCounter?_testCounter="0"+_testCounter:_.noop(),console.log(_.cconsole.color.red+"Test (#"+_testCounter+") "+a+" failed"+_.cconsole.color.standard),process.stdout.write("Expecting: "+_.cconsole.color.magenta+
String(c).replace(/(\r\n|\n\r|\r|\n)/g,"")+_.cconsole.color.standard+"; Got: "+_.cconsole.color.red+b+_.cconsole.color.standard+"\r"),_testCounter++,_testFailed++)}},_timeoutCounter*delay,d,b,e);_timeoutCounter++}__RunTest("_._lastObj",void 0);__RunTest("_._modLoaded",void 0);__RunTest("_._eventStore",void 0);__RunTest("_.length",1);__RunTest("_.params",void 0);__RunTest("_('.MyParam').params",void 0);__RunTest("_.version",_.version);__RunTest("_.revision",_.revision);__RunTest("_.fullversion",_.fullversion);
__RunTest("_.isBeta",_.isBeta);__RunTest("_.isAlpha",_.isAlpha);__RunTest("_.isCompiled",_.isCompiled);__RunTest("_.isStable",_.isStable);__RunTest("_.nodeJS",!0);__RunTest("_.ScriptRX",_.ScriptRX);__RunTest("_.JSONRX",_.JSONRX);__RunTest("_.emoij.nerd","\ud83e\udd13");__RunTest("_.emoij.smilie","\ud83d\ude03");__RunTest("_.emoij.dsmilie","\ud83d\ude00");__RunTest("_.emoij.heart","\u2764\ufe0f");__RunTest("_.emoij.brokenheart","\ud83d\udc94");__RunTest("_.browser['ie']",!1);
__RunTest("_.browser['firefox']",!1);__RunTest("_.browser['safari']",!1);__RunTest("_.browser['opera']",!1);__RunTest("_.browser['edge']",!1);__RunTest("_.browser['chrome']",!1);__RunTest("_.browser['userAgent']","Node.js Node.js Node.js");__RunTest("_.browser['supportTouch']",!1);__RunTest("_.getBrowser","Node.js");__RunTest("_.$('TEST')","undefined");__RunTest("_.extend(true, {apple:0, chicken:{weight:52, price:100}, cherry:97},{chicken:{price:200}, durian:100})","[object Object]");
__RunTest("_.isArray([])",!0);__RunTest("_.isArray(null)",!1);__RunTest("_.getCookie('Cookiemonster')",!1);__RunTest("_.setCookie('Cookiemonster', 'Cookiemonster is cool')",!1);__RunTest("_.getCookie('Cookiemonster')",!1);__RunTest("_('.x').toggle()",!1);__RunTest("_('.x').on('click', function (){console.log('clicked on x')})",!1);__RunTest("_.noop()",void 0);__RunTest("_.supportTouch()",!1);__RunTest('_("<b>Hi!</b>").appendTo(".inner")',!1);
__RunTest("_._error('#IGNORE#ME', 'SOME TERRIBLE THING HAPPENED!')",null);__RunTest("_.isFunction(function () {})",!0);__RunTest("_.isFunction(false)",!1);__RunTest("_.type(function () { })","function");__RunTest("_.type({})","object");__RunTest("_.type([])","array");__RunTest("_.escapeForRegex('myPotensialRege\\\\\\'xUnSafeString')","myPotensialRege\\\\'xUnSafeString");__RunTest("_.isPlainObject(function () {})",!1);__RunTest("_.isPlainObject({})",!0);__RunTest("_.isPlainObject([])",!1);
__RunTest("_.require(['a', 'r', 'ra', 'y'], function () { doSomeThing(); })",null);__RunTest("_.format('my %s', 'wesley')","my wesley");__RunTest("_('.wrapper').hide()",!1);__RunTest("_('.wrapper').html('xxxx')",!1);__RunTest("_('.wrapper').html('xxxx', true)",!1);__RunTest("_('.wrapper').html()",!1);__RunTest("_('.wrapper').show()",!1);__RunTest("_.framebreak()",!1);__RunTest("_('.wrapper').ajaxPOST('form', function(x){console.log(x)})",!1);
__RunTest("_('.wrapper').ajax('https://www.wdgwv.com/conditions/noHTML')",!1);__RunTest("_.noConflict()",_);__RunTest("_.isLocal()",!0);__RunTest("_.requireSSL()");__RunTest("_.loadExtension(['a', 'r', 'ra', 'y'], function () { doSomeThing(); })",null);__RunTest("_.isUndefined(false)",!1);__RunTest("_.isUndefined(true)",!1);__RunTest("_.isUndefined(undefined)",!0);__RunTest("_.isEmpty(undefined)",!1);__RunTest("_.isEmpty('')",!0);__RunTest("_.isBlank(undefined)",!1);__RunTest("_.isBlank('')",!0);
__RunTest("_.getFileSize('https://www.wdgwv.com/logo.png')",null);__RunTest("_('.wrapper').stripTags()",!1);__RunTest("_('.wrapper').stripScripts()",!1);__RunTest("_('.wrapper').css('color: red;')",!1);__RunTest("_.escapeHTML('<&>')","&lt;&amp;&gt;");__RunTest("_.unescapeHTML('&lt;&amp;&gt;')","<&>");__RunTest("TOTAL","TOTAL");
