//# sourceMappingURL=node.js.map
var _=require("./_.js");console.log("**");console.log("**                         _");console.log("**                        (_)");console.log("**                         _    _____");console.log("**                        | |  / ____|");console.log("**                        | |  | (___");console.log("**                    _   | |  \\___  \\");console.log("**     ______    _   | |__| |  ____) |");console.log("**    |______|  (_)   \\____/  |______/");
_.version.match(/b/)?console.log("**                         v"+_.version.split("b")[0]+" Beta"):console.log("**                      v"+_.version+" Release");console.log("**              JS Standard Code Style");console.log("**");console.log("**    This is the Node.js init file.");console.log("**    To use _.js in your project use:");console.log("**       var _ = require('./_.js')");console.log("**");console.log("**");console.log(_.runTest("a","b"));var _testCounter=1,_testPassed=0,_testFailed=0;
function __RunTest(a,b){"TOTAL"===a&&"TOTAL"===b?(console.log("All tests finished"),0<_testFailed?(console.log(_.cconsole.color.green+_testPassed+" tests Passed (? %)"+_.cconsole.color.standard),console.log(_.cconsole.color.red+_testFailed+" tests Failed (? %)"+_.cconsole.color.standard)):console.log(_.cconsole.color.green+_testPassed+" (ALL) tests Passed (100 %)"+_.cconsole.color.standard)):_.runTest(eval(a),b)?(console.log(_.cconsole.color.green+"Test "+a+" (#"+_testCounter+") passed"+_.cconsole.color.standard),
console.log("Expecting: "+_.cconsole.color.green+b+_.cconsole.color.standard+"; Got: "+_.cconsole.color.green+eval(a)+_.cconsole.color.standard+" "),_testCounter++,_testPassed++):(console.log(_.cconsole.color.red+"Test "+a+" (#"+_testCounter+") failed"+_.cconsole.color.standard),console.log("Expecting: "+_.cconsole.color.magenta+b+_.cconsole.color.standard+"; Got: "+_.cconsole.color.red+eval(a)+_.cconsole.color.standard+" "),_testCounter++,_testFailed++)}__RunTest("_._lastObj",void 0);
__RunTest("_._modLoaded",void 0);__RunTest("_._eventStore",void 0);__RunTest("_.length",1);__RunTest("_.params",void 0);__RunTest("_.version",_.version);__RunTest("_.revision",_.revision);__RunTest("_.fullversion",_.fullversion);__RunTest("_.isBeta",_.isBeta);__RunTest("_.isAlpha",_.isAlpha);__RunTest("_.isCompiled",_.isCompiled);__RunTest("_.isStable",_.isStable);__RunTest("_.nodeJS",!0);__RunTest("_.ScriptRX",_.ScriptRX);__RunTest("_.JSONRX",_.JSONRX);__RunTest("_.emoij.nerd","\ud83e\udd13");
__RunTest("_.emoij.smilie","\ud83d\ude03");__RunTest("_.emoij.dsmilie","\ud83d\ude00");__RunTest("_.emoij.heart","\u2764\ufe0f");__RunTest("_.emoij.brokenheart","\ud83d\udc94");__RunTest("_.browser['ie']",!1);__RunTest("_.browser['firefox']",!1);__RunTest("_.browser['safari']",!1);__RunTest("_.browser['opera']",!1);__RunTest("_.browser['edge']",!1);__RunTest("_.browser['chrome']",!1);__RunTest("_.browser['userAgent']","Node.js Node.js Node.js");__RunTest("_.browser['supportTouch']",!1);
__RunTest("_.getBrowser","Node.js");__RunTest("_.$('TEST')","undefined");__RunTest("_.extend(true, {apple:0, chicken:{weight:52, price:100}, cherry:97},{chicken:{price:200}, durian:100})","[object Object]");__RunTest("_.isArray([])",!0);__RunTest("_.isArray(null)",!1);__RunTest("_.getCookie('Cookiemonster')",!1);__RunTest("_.setCookie('Cookiemonster', 'Cookiemonster is cool')",!1);__RunTest("_.getCookie('Cookiemonster')",!1);__RunTest("_('.x').toggle()",!1);
__RunTest("_('.x').on('click', function (){console.log('clicked on x')})",!1);__RunTest("_.noop()",void 0);__RunTest("_.supportTouch()",!1);__RunTest('_("<b>Hi!</b>").appendTo(".inner")',!1);__RunTest("_._error('#IGNORE#ME', 'SOME TERRIBLE THING HAPPENED!')",null);__RunTest("_.isFunction(function () {})",!0);__RunTest("_.isFunction(false)",!1);__RunTest("_.type(function () { })","function");__RunTest("_.type({})","object");__RunTest("_.type([])","array");
__RunTest("_.escapeForRegex('myPotensialRege\\\\\\'xUnSafeString')","myPotensialRege\\\\'xUnSafeString");__RunTest("_.isPlainObject(function () {})",!1);__RunTest("_.isPlainObject({})",!0);__RunTest("_.isPlainObject([])",!1);__RunTest("_.require(['a', 'r', 'ra', 'y'], function () { doSomeThing(); })",null);__RunTest("_.format('my %s', 'wesley')","my wesley");__RunTest("_('.wrapper').hide()",!1);__RunTest("TOTAL","TOTAL");var x=_.browser.userAgent;console.log(_.cconsole.color.yellow+x);
console.log(_.cconsole.color.yellow+typeof x);
